language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]] ;then pip install unittest2 ;fi"
  - "pip install ephem"
# command to run tests, e.g. python setup.py test
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]] ;then unit2 discover tests ;else python -m unittest discover tests; fi"
